/* jshint esversion: 6 */

import Head from 'next/head';
import { Inter } from '@next/font/google';
import NavAuth from '../components/tutorial/NavAuth';

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  return (
    <>
      <Head>
        <title>Northware Suite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavAuth />
    </>
  )
}
